services:
  postapp:
    image: ghcr.io/chatgut/post-service-aj:main@sha256:bcae4b8db3b89db8476c311e59fe202f25089cf46c6fa0a8b9127c1100b62205
    container_name: postservice
    ports:
      - "8090:8080"
    depends_on:
      - mongodb
    environment:
      - 'SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/messages'
    restart: on-failure
  mongodb:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    volumes:
        - mongodb:/data/db
    environment:
      MONGO_INITDB_DATABASE: messages
# used for testing purposes, running 2 microservices

#  usersapp:
#    image: ghcr.io/chatgut/userservice:1.0
#    container_name: userservice
#    ports:
#      - "8002:8002"
#    depends_on:
#      - dbUsers
#    environment:
#      DB_URL: jdbc:mysql://dbUsers:3306/userService
#      DB_USER: developer
#      DB_PASSWORD: password
#
#  dbUsers:
#    image: mysql:latest
#    environment:
#      MYSQL_ROOT_HOST: '%'
#      MYSQL_ROOT_USER: root
#      MYSQL_ROOT_PASSWORD: password
#      MYSQL_DATABASE: userService
#      MYSQL_PASSWORD: password
#      MYSQL_USER: developer
#    volumes:
#      - dbUsers:/var/lib/mysql

volumes:
  dbUsers:
  mongodb: