
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postservice
  labels:
    app: postservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postservice
  template:
    metadata:
      name: postservice
      labels:
        app: postservice
    spec:
      containers:
        - name: postservice
          image: ghcr.io/chatgut/post-service-aj:main
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: 'mongodb://mongodb:27017/messages'
      restartPolicy: Always