---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongodb-persistent-storage
          persistentVolumeClaim:
            claimName: mongodb-pv-claim
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postservice
  labels:
    app: postservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postservice
  template:
    metadata:
      name: postservice
      labels:
        app: postservice
    spec:
      containers:
        - name: postservice
          image: ghcr.io/chatgut/post-service-aj:main
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always


      